name: Environment Demo

on:
  pull_request:
    branches:
      - dev

jobs:
  target_env:
    runs-on: ubuntu-latest

    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
      fe_environment: ${{ steps.set-env.outputs.fe_environment }}

    steps:
      - name: Determine Environment
        id: set-env
        run: |
          case "${{ github.base_ref }}" in
            dev)
              ENVIRONMENT="dev"
              FE_ENVIRONMENT="fedev"
              ;;
            *)
              echo "Unsupported target branch"
              exit 1
              ;;
          esac

          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "fe_environment=$FE_ENVIRONMENT" >> $GITHUB_OUTPUT

  hello_world:
    needs: target_env
    runs-on: ubuntu-latest

    environment:
      name: ${{ needs.target_env.outputs.environment }}

    steps:
      - name: Print Environment
        run: |
          echo "Hello World"
          echo "Environment: ${{ needs.target_env.outputs.environment }}"

  fe_hello_world:
    needs: target_env
    runs-on: ubuntu-latest

    environment:
      name: ${{ needs.target_env.outputs.fe_environment }}

    steps:
      - name: Print FE Environment
        run: |
          echo "Hello World"
          echo "Environment: ${{ needs.target_env.outputs.fe_environment }}"
